apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: logging
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      initContainers:
      - name: copy-fluentd-config
        image: busybox
        command: ['sh', '-c', 'cp /config-volume/* /etc/fluentd']
        volumeMounts:
          - name: fluentd-config
            mountPath: /config-volume
          - name: config
            mountPath: /etc/fluentd
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.4.2-debian-elasticsearch-1.1
        securityContext:
          privileged: true
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "10.91.11.155"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENT_ELASTICSEARCH_RELOAD_CONNECTIONS
            value: "false"
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
        - name: erslog
          mountPath: /var/log/APPLICATION_LOG_PATH ## TOBE UPDATED The hostpath need to be updated with proper path of the application log files
        - name:  config
          mountPath: /fluentd/etc
          readOnly: false
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: erslog
        hostPath:
          path: /var/log/AAPPLICATION_LOG_PATH ## TOBE UPDATED The hostpath need to be updated with proper path of the application log files 
      - name: fluentd-config
        configMap:
          name: fluentd-config
      - name: config
        emptyDir: {}
